### ISSUE TITLE
Current section on commenting perpetuates a damaging narrative

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/rsd-engineeringcourse#36]
I'm so surprised that this course is teaching data science learners not to comment their code.

https://alan-turing-institute.github.io/rsd-engineeringcourse/ch05construction/03comments.html

I think this quote in particular is appalling.

> The proper use of comments is to compensate for our failure to express yourself in code. Note that I used the word failure. I meant it. Comments are always failures.

This narrative around comments being failures, that only people who "aren't real coders" is something I've been giving talks _against_ for more than 7 years. This chapter alone is enough to make someone stop trying to learn this new skill, feel undervalued and like they don't fit into the clique. Nevermind whether they will feel confident sharing their code openly or contributing to an open source project. It is one of the ultimate bro behaviours in data science: https://thepsychologist.bps.org.uk/volume-33/november-2020/bropenscience-broken-science

Who is the audience for this course? Who benefits from being told that the comments that make their code easier for _themselves and others_ to read make them a "failure at coding"?

Is this section destined to stay in this course? Can it be updated? Who is reviewing this course material from a perspective of equity and inclusion?

**Comment by triangle-man** [comment]
FWIW, I didn't read this section as being an injuction against comments _per se_. The final two sections give examples of good commenting practice, for example; and it starts by enumerating the reasons for writing comments. 

It _is_ very concerned with bashing poor commenting practice, as the author(s) see it, and I can certainly see how that could both discourage a novice and annoy a more experienced programmer. Perhaps it would be better written with the good practice first, somewhat enlarged; and then a briefer section on "things to avoid"?

If I were writing about comments I think I would also try to think about the differences in use between: comments in "library" code; prose which documents the code; and the text blocks that separate code fragments in notebooks. I'd also think about the extent to which it's possible to implement Knuth's ideas of literate programming these days. (Answer: it depends.) 

I'm unlikely to have time to put my money where my mouth is here, but I would guess that pull requests would be gratefully accepted.

**Comment by KirstieJane** [comment]
Two points.

This comment _did_ discourage a novice, that's how I heard about the section. It also _did_ really annoy me, who this chapter would almost certainly consider to not be a sufficiently experienced programmer but who has written enough code to not be a novice.

I think a step beyond @triangle-man's suggestion is to think less about "good" comments and "bad" comments regardless of where they are being found, and focus more on the _audience_ reading the comment. Who does the participant think is going to be reading this code in the future? Most likely themselves, but maybe another member in their team? Are they writing for strangers? Why? What are their skills? What will they find the comments useful for?

**Comment by jamespjh** [comment]
I wrote this. (In 2012) 

I didn't present it this year. 

I stand by the thrust of it - that comments are better replaced by readable code, where you use variable names and function names to express what you might have expressed in comments, using comments where you can't find a way to do that.

When I teach it, I emphasise that the quote is probably taking things too far, but is illustrating an important point.

Happy to remove the quote and it's language of 'failure' based on your advice KW - that might be seen as a demotivator and taken the wrong way.

Happy to discuss.

We've discussed again and again the balance between expressing the fact that there is a way to do things well, and doing well is something we should be excited to achieve, without turning off or excluding beginners. I'm happy to be told that the current tone doesn't strike that balance well.

But I do think we do have to teach that good coding style is *not* commenting, or that people can think they've achieved good style without commenting. And we do have to teach that good style is a thing people should be excited to aim for.

**Comment by nbarlowATI** [comment]
FWIW, I taught that section yesterday, and I believe/hope I emphasised that in my view that quote represents a pretty extreme, purist viewpoint, and to be fair, the notebook itself does say immediately after the quote:  _"writing "self-documenting" code is very hard, so do comment if you're unsure!"_.    If that aspect didn't come across well enough and students were discouraged, I can only apologise to them (of course, discouraging people is absolutely the last thing we want to do!)

I have a PR open (#35) for fixes/improvements to this chapter, where I have just committed a change that removes that quote, adds a short section on who we write comments for, and replaces "bad" with "possibly unnecessary/extraneous".    Further comments/commits on that PR are very welcome!

**Comment by jamespjh** [comment]
I just had a good long chat with @KirstieJane - I'll pull your branch @nbarlowATI and have a fiddle.

PS: I agree with you that your classroom presentation mediated the issue well!

**Comment by jamespjh** [comment]
PR #35 addresses. I put the quote back with caveating - happy to be told to just delete.

**Comment by jamespjh** [comment]
@dpshelio views from the other fork?
